# -*- coding: utf-8 -*-
"""WILLY V8 c++ version

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOfisPgH1ndACVeyAWoSpJijl49MEBir
"""

!pip install python-chess
!apt-get install -y stockfish

# Commented out IPython magic to ensure Python compatibility.
# %%writefile willy_titan.cpp
# #include <iostream>
# #include <string>
# 
# int main(int argc, char* argv[]) {
#     // If no board state provided, return neutral
#     if (argc < 2) { std::cout << "0"; return 0; }
# 
#     std::string fen = argv[1];
#     int score = 0;
# 
#     // Titan Heuristic: Aggressive Material Weighting
#     for (char c : fen) {
#         if (c == ' ') break;
#         if (c == 'q') score += 950;  // Willy's Queen
#         if (c == 'r') score += 500;  // Willy's Rook
#         if (c == 'p') score += 100;  // Willy's Pawn
#         if (c == 'Q') score -= 950;  // Opponent's Queen
#         if (c == 'P') score -= 100;
#     }
# 
#     std::cout << score;
#     return 0;
# }

!g++ -O3 willy_titan.cpp -o willy_titan
!chmod +x willy_titan

import chess
import chess.engine
import pickle
import os
import math
import time
import random
from IPython.display import HTML, display
from google.colab import output, drive

# --- 0. DRIVE & MAX STATS SETUP ---
drive.mount('/content/drive', force_remount=True)
DB_PATH = "/content/drive/MyDrive/willy_brain_permanent.pkl"

class WillyV8_Grandmaster:
    def __init__(self):
        # MAXED OUT GRANDMASTER STATS
        self.stats = {"games": 0, "wins": 0}
        self.piece_values = {
            chess.PAWN: 100, chess.KNIGHT: 310, chess.BISHOP: 335,
            chess.ROOK: 500, chess.QUEEN: 950, chess.KING: 20000
        }
        self.save_brain()

        # --- THE 100+ MOVE OPENING BOOK ---
        self.book = {
            # White Openings
            "": ["e2e4", "d2d4", "c2c4", "g1f3"],

            # Black Responses to e4
            "e2e4": ["e7e5", "c7c5", "e7e6", "c7c6"], # Open Game, Sicilian, French, Caro-Kann
            "e2e4 e7e5": ["g1f3", "f1c4", "f2f4", "b1c3"],
            "e2e4 c7c5": ["g1f3", "b1c3", "c2c3"],
            "e2e4 e7e6": ["d2d4", "g1f3"],
            "e2e4 c7c6": ["d2d4", "b1c3"],

            # Black Responses to d4
            "d2d4": ["d7d5", "g8f6", "e7e6", "f7f5"], # Queen's Pawn, Indian, Dutch
            "d2d4 d7d5": ["c2c4", "g1f3", "c1f4"], # QG, London
            "d2d4 g8f6": ["c2c4", "g1f3"],

            # Deeper e4 e5 lines
            "e2e4 e7e5 g1f3": ["b8c6", "g8f6", "d7d6"],
            "e2e4 e7e5 g1f3 b8c6": ["f1b5", "f1c4", "d2d4", "c2c3"], # Ruy Lopez, Italian, Scotch
            "e2e4 e7e5 g1f3 b8c6 f1b5": ["a7a6", "g8f6", "f8c5"], # Ruy Lopez Defenses
            "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6": ["b5a4", "b5c6"],
            "e2e4 e7e5 g1f3 b8c6 f1b5 a7a6 b5a4": ["g8f6", "d7d6"],
            "e2e4 e7e5 g1f3 b8c6 f1c4": ["f8c5", "g8f6"], # Italian Main lines
            "e2e4 e7e5 g1f3 b8c6 f1c4 f8c5": ["c2c3", "d2d3", "b2b4"], # Evans Gambit included

            # Deeper Sicilian lines
            "e2e4 c7c5 g1f3": ["d7d6", "b8c6", "e7e6"],
            "e2e4 c7c5 g1f3 d7d6": ["d2d4", "f1b5"],
            "e2e4 c7c5 g1f3 d7d6 d2d4": ["c5d4"],
            "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4": ["f3d4"],
            "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4": ["g8f6"],
            "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6": ["b1c3"],
            "e2e4 c7c5 g1f3 d7d6 d2d4 c5d4 f3d4 g8f6 b1c3": ["a7a6", "g7g6", "e7e6"], # Najdorf, Dragon

            # Deeper d4 d5 lines
            "d2d4 d7d5 c2c4": ["e7e6", "c7c6", "d5c4"], # QGD, Slav, QGA
            "d2d4 d7d5 c2c4 e7e6": ["b1c3", "g1f3"],
            "d2d4 d7d5 c2c4 e7e6 b1c3": ["g8f6", "f8e7"],
            "d2d4 d7d5 c2c4 c7c6": ["g1f3", "b1c3"],

            # Deeper Indian lines
            "d2d4 g8f6 c2c4": ["e7e6", "g7g6"],
            "d2d4 g8f6 c2c4 e7e6": ["b1c3", "g1f3", "g2g3"],
            "d2d4 g8f6 c2c4 e7e6 b1c3": ["f8b4", "d7d5"], # Nimzo-Indian
            "d2d4 g8f6 c2c4 g7g6": ["b1c3", "g1f3"],
            "d2d4 g8f6 c2c4 g7g6 b1c3": ["f8g7", "d7d5"], # King's Indian, Grunfeld
            "d2d4 g8f6 c2c4 g7g6 b1c3 f8g7": ["e2e4", "g1f3"],

            # English
            "c2c4": ["e7e5", "c7c5", "g8f6", "e7e6"],
            "c2c4 e7e5": ["b1c3", "g2g3"]
        }

    def save_brain(self):
        with open(DB_PATH, 'wb') as f:
            pickle.dump({'stats': self.stats}, f)

    def evaluate_board(self, board):
        if board.is_checkmate(): return 999999 if board.turn == chess.WHITE else -999999
        if board.is_stalemate() or board.is_insufficient_material(): return 0

        score = 0
        white_material = 0
        for sq, piece in board.piece_map().items():
            val = self.piece_values.get(piece.piece_type, 0)
            if piece.color == chess.WHITE: white_material += val

            if piece.color == chess.BLACK:
                score += val
                if piece.piece_type == chess.PAWN:
                    score += (7 - chess.square_rank(sq)) * 15
            else:
                score -= val

        # ENDGAME BOXING
        if white_material < 1500:
            w_king, b_king = board.king(chess.WHITE), board.king(chess.BLACK)
            score += max(abs(chess.square_rank(w_king) - 3.5), abs(chess.square_file(w_king) - 3.5)) * 15
            score += (14 - chess.distance(b_king, w_king)) * 5

        return score

    def check_opening_book(self, board):
        # Convert move history to a string to check against the dictionary
        history = " ".join([move.uci() for move in board.move_stack])
        if history in self.book:
            candidates = self.book[history]
            legal_moves = [chess.Move.from_uci(m) for m in candidates if chess.Move.from_uci(m) in board.legal_moves]
            if legal_moves:
                return random.choice(legal_moves)
        return None

    def minimax(self, board, depth, alpha, beta, maximizing):
        if depth == 0 or board.is_game_over(): return self.evaluate_board(board)
        moves = sorted(board.legal_moves, key=lambda m: board.is_capture(m), reverse=True)

        if maximizing:
            max_eval = -math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, False)
                board.pop()
                max_eval = max(max_eval, eval)
                alpha = max(alpha, eval)
                if beta <= alpha: break
            return max_eval
        else:
            min_eval = math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, True)
                board.pop()
                min_eval = min(min_eval, eval)
                beta = min(beta, eval)
                if beta <= alpha: break
            return min_eval

    def get_move(self, board):
        # 1. CHECK OPENING BOOK FIRST
        book_move = self.check_opening_book(board)
        if book_move:
            time.sleep(0.3) # Tiny delay to simulate playing
            return book_move

        # 2. FALLBACK TO MINIMAX SEARCH
        best_move = None
        max_val = -math.inf
        for move in board.legal_moves:
            board.push(move)
            val = self.minimax(board, 3, -math.inf, math.inf, False)
            board.pop()
            if val > max_val:
                max_val = val
                best_move = move
        return best_move if best_move else random.choice(list(board.legal_moves))

# --- 1. BRIDGE & SIMULATION ---
bot = WillyV8_Grandmaster()
board = chess.Board()

def get_status():
    if board.is_checkmate(): return "CHECKMATE!"
    if board.is_stalemate(): return "STALEMATE!"
    if board.is_game_over(): return "DRAW / GAME OVER"
    return "LIVE"

def handle_move(move_uci):
    global board
    if move_uci == "RESET":
        board.reset()
        return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|READY"
    try:
        move = chess.Move.from_uci(move_uci)
        if move in board.legal_moves:
            board.push(move)
            if not board.is_game_over():
                board.push(bot.get_move(board))
    except: pass

    # If Willy played from book, let the user know
    history = " ".join([m.uci() for m in board.move_stack[:-1]])
    status = get_status()
    if status == "LIVE" and history in bot.book:
        status = "BOOK MOVE PLAYED"

    return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|{status}"

def run_sims(count=10):
    global board
    count = int(count)
    is_spectator = True if count <= 10 else False
    try:
        engine = chess.engine.SimpleEngine.popen_uci("/usr/games/stockfish")
        engine.configure({"Skill Level": 5})
        for _ in range(count):
            board.reset()
            while not board.is_game_over() and board.fullmove_number < 100:
                move = engine.play(board, chess.engine.Limit(time=0.01)).move if board.turn == chess.WHITE else bot.get_move(board)
                board.push(move)
                if is_spectator:
                    output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, '{get_status()}')")
                    time.sleep(0.4)

            final_status = get_status()
            output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, '{final_status}')")
            bot.stats["games"] += 1
            if board.result() == "0-1": bot.stats["wins"] += 1
            bot.save_brain()
            if is_spectator: time.sleep(2.0)

        engine.quit()
    except Exception as e: print(f"Error: {e}")

output.register_callback('notebook.handle_move', handle_move)
output.register_callback('notebook.run_sims', run_sims)

# --- 2. CLASSIC UI WITH BUTTONS (WHITE ON BOTTOM) ---
html_ui = f"""
<div style="text-align:center; background:#111; padding:20px; color:#0f0; font-family:monospace; border-radius:15px; border: 2px solid #333;">
    <h2 style="color:#fff; margin-bottom:5px;">WILLY V8.2: GRANDMASTER </h2>
    <div id="status_bar" style="background:#222; color:#ff0; padding:8px; margin-bottom:10px; border: 1px solid #444; font-weight:bold; font-size:1.2em;">SYSTEM READY</div>
    <p>GAMES: <span id="g_count">{bot.stats['games']}</span> | WINS: <span id="w_count">{bot.stats['wins']}</span></p>
    <div id="board" style="width:380px; margin:auto; border: 1px solid #555;"></div>
    <div style="margin-top:20px;">
        <button onclick="startSims(10)" style="padding:10px; background:#0f0; border:none; cursor:pointer; font-weight:bold; color:#000;">SPECTATE 10</button>
        <button onclick="resetGame()" style="padding:10px; background:#444; color:#fff; border:none; cursor:pointer;">RESET 1V1</button>
        <button onclick="startSims(500)" style="padding:10px; background:#222; color:#0f0; border:1px solid #0f0; cursor:pointer;">GRIND 500</button>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.css">
<script>
var board = Chessboard('board', {{
    draggable: true,
    position: 'start',
    orientation: 'white',  // <-- FLIPPED FOR YOU TO PLAY WHITE
    onDrop: function(source, target) {{
        var move = source + target;
        google.colab.kernel.invokeFunction('notebook.handle_move', [move], {{}}).then(function(result) {{
            var parts = result.data['text/plain'].split('|');
            updateUI(parts[0].replace(/'/g, ""), parts[1], parts[2], parts[3].replace(/'/g, ""));
        }});
    }},
    pieceTheme: 'https://chessboardjs.com/img/chesspieces/wikipedia/{{piece}}.png'
}});

function updateUI(fen, g, w, s) {{
    board.position(fen);
    $('#g_count').text(g);
    $('#w_count').text(w);

    let statusEl = $('#status_bar');
    statusEl.text(s);

    if (s.includes("CHECKMATE")) {{
        statusEl.css({{"background": "#800", "color": "#fff"}});
    }} else if (s.includes("STALEMATE") || s.includes("DRAW")) {{
        statusEl.css({{"background": "#550", "color": "#fff"}});
    }} else if (s.includes("BOOK MOVE")) {{
        statusEl.css({{"background": "#004400", "color": "#0f0"}}); // Turns dark green when he plays theory
    }} else if (s.includes("READY")) {{
        statusEl.css({{"background": "#222", "color": "#ff0"}});
    }} else {{
        statusEl.css({{"background": "#222", "color": "#0f0"}});
    }}
}}

function resetGame() {{
    google.colab.kernel.invokeFunction('notebook.handle_move', ['RESET'], {{}}).then(function(r){{
        board.start();
        updateUI('start', $('#g_count').text(), $('#w_count').text(), "READY");
    }});
}}
function startSims(c) {{ google.colab.kernel.invokeFunction('notebook.run_sims', [c], {{}}); }}
</script>
"""
display(HTML(html_ui))