# -*- coding: utf-8 -*-
"""WILLY V10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uOfisPgH1ndACVeyAWoSpJijl49MEBir
"""

!pip install python-chess
!apt-get install -y stockfish

# Commented out IPython magic to ensure Python compatibility.
# %%writefile willy_titan.cpp
# #include <iostream>
# #include <string>
# 
# int main(int argc, char* argv[]) {
#     // If no board state provided, return neutral
#     if (argc < 2) { std::cout << "0"; return 0; }
# 
#     std::string fen = argv[1];
#     int score = 0;
# 
#     // Titan Heuristic: Aggressive Material Weighting
#     for (char c : fen) {
#         if (c == ' ') break;
#         if (c == 'q') score += 950;  // Willy's Queen
#         if (c == 'r') score += 500;  // Willy's Rook
#         if (c == 'p') score += 100;  // Willy's Pawn
#         if (c == 'Q') score -= 950;  // Opponent's Queen
#         if (c == 'P') score -= 100;
#     }
# 
#     std::cout << score;
#     return 0;
# }

!g++ -O3 willy_titan.cpp -o willy_titan
!chmod +x willy_titan

# -*- coding: utf-8 -*-
"""WILLY V10: + """

!pip install python-chess
!apt-get install -y stockfish

# --- 1. THE C++ POSITIONAL ENGINE
with open("willy_eval.cpp", "w") as f:
    f.write("""
#include <iostream>
#include <string>
#include <vector>

const int pawnEvalWhite[64] = {
    0,  0,  0,  0,  0,  0,  0,  0,
    50, 50, 50, 50, 50, 50, 50, 50,
    10, 10, 20, 30, 30, 20, 10, 10,
     5,  5, 10, 25, 25, 10,  5,  5,
     0,  0,  0, 20, 20,  0,  0,  0,
     5, -5,-10,  0,  0,-10, -5,  5,
     5, 10, 10,-20,-20, 10, 10,  5,
     0,  0,  0,  0,  0,  0,  0,  0
};

const int knightEval[64] = {
    -50,-40,-30,-30,-30,-30,-40,-50,
    -40,-20,  0,  0,  0,  0,-20,-40,
    -30,  0, 10, 15, 15, 10,  0,-30,
    -30,  5, 15, 20, 20, 15,  5,-30,
    -30,  0, 15, 20, 20, 15,  0,-30,
    -30,  5, 10, 15, 15, 10,  5,-30,
    -40,-20,  0,  5,  5,  0,-20,-40,
    -50,-40,-30,-30,-30,-30,-40,-50
};

int get_piece_value(char piece) {
    switch (tolower(piece)) {
        case 'p': return 100;
        case 'n': return 320;
        case 'b': return 330;
        case 'r': return 500;
        case 'q': return 900;
        case 'k': return 20000;
        default: return 0;
    }
}

int main(int argc, char* argv[]) {
    if (argc < 2) return 0;
    std::string fen = argv[1];
    int score = 0;
    int square = 0;
    for (char c : fen) {
        if (c == ' ') break;
        if (c == '/') continue;
        if (isdigit(c)) {
            square += (c - '0');
        } else {
            int val = get_piece_value(c);
            int pst_bonus = 0;
            if (tolower(c) == 'p') pst_bonus = pawnEvalWhite[square];
            if (tolower(c) == 'n') pst_bonus = knightEval[square];

            if (islower(c)) score += val + pst_bonus;
            else score -= val + pst_bonus;
            square++;
        }
    }
    std::cout << score;
    return 0;
}
""")

!g++ -O3 willy_eval.cpp -o willy_eval
!chmod +x willy_eval

import chess
import chess.engine
import subprocess
import math
import pickle
import time
from IPython.display import HTML, display
from google.colab import output, drive

# --- DRIVE MOUNT FOR STATS ---
drive.mount('/content/drive', force_remount=True)
DB_PATH = "/content/drive/MyDrive/willy_v15_brain.pkl"

# --- 2. THE PYTHON DEEP THINKER ---
class WillyV15_Deep:
    def __init__(self):
        self.engine_path = "./willy_eval"
        self.stats = {"games": 0, "wins": 0}
        try:
            with open(DB_PATH, 'rb') as f:
                data = pickle.load(f)
                self.stats = data.get('stats', {"games": 0, "wins": 0})
        except:
            pass

    def save_brain(self):
        with open(DB_PATH, 'wb') as f:
            pickle.dump({'stats': self.stats}, f)

    def get_fast_eval(self, fen):
        res = subprocess.run([self.engine_path, fen], capture_output=True, text=True)
        return int(res.stdout.strip()) if res.stdout.strip() else 0

    def quiescence_search(self, board, alpha, beta, maximizing):
        stand_pat = self.get_fast_eval(board.fen())
        if maximizing:
            if stand_pat >= beta: return beta
            if alpha < stand_pat: alpha = stand_pat
            for move in board.legal_moves:
                if board.is_capture(move):
                    board.push(move)
                    score = self.quiescence_search(board, alpha, beta, False)
                    board.pop()
                    if score >= beta: return beta
                    if score > alpha: alpha = score
            return alpha
        else:
            if stand_pat <= alpha: return alpha
            if beta > stand_pat: beta = stand_pat
            for move in board.legal_moves:
                if board.is_capture(move):
                    board.push(move)
                    score = self.quiescence_search(board, alpha, beta, True)
                    board.pop()
                    if score <= alpha: return alpha
                    if score < beta: beta = score
            return beta

    def minimax(self, board, depth, alpha, beta, maximizing):
        if board.is_checkmate(): return 999999 if maximizing else -999999
        if depth == 0: return self.quiescence_search(board, alpha, beta, maximizing)

        moves = sorted(board.legal_moves, key=lambda m: board.is_capture(m), reverse=True)

        if maximizing:
            best = -math.inf
            for m in moves:
                board.push(m)
                best = max(best, self.minimax(board, depth-1, alpha, beta, False))
                board.pop()
                alpha = max(alpha, best)
                if beta <= alpha: break
            return best
        else:
            best = math.inf
            for m in moves:
                board.push(m)
                best = min(best, self.minimax(board, depth-1, alpha, beta, True))
                board.pop()
                beta = min(beta, best)
                if beta <= alpha: break
            return best

    def get_move(self, board):
        best_move = None
        best_val = -math.inf
        for m in board.legal_moves:
            board.push(m)
            val = self.minimax(board, 2, -math.inf, math.inf, False)
            board.pop()
            if val > best_val:
                best_val, best_move = val, m
        return best_move

# --- 3. UI & BRIDGE
bot = WillyV15_Deep()
board = chess.Board()

def get_status():
    if board.is_checkmate(): return "CHECKMATE!"
    if board.is_stalemate(): return "STALEMATE!"
    if board.is_game_over(): return "DRAW / GAME OVER"
    return "LIVE"

def handle_move(move_uci):
    global board
    if move_uci == "RESET":
        board.reset()
        return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|READY"
    try:
        move = chess.Move.from_uci(move_uci)
        if move not in board.legal_moves:
            move = chess.Move.from_uci(move_uci + "q")
        if move in board.legal_moves:
            board.push(move)
            if not board.is_game_over():
                board.push(bot.get_move(board))
    except: pass

    return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|{get_status()}"

def run_sims(count=10):
    global board
    count = int(count)
    is_spectator = True if count <= 10 else False
    try:
        engine = chess.engine.SimpleEngine.popen_uci("/usr/games/stockfish")
        engine.configure({"Skill Level": 5}) # Sparring partner level
        for _ in range(count):
            board.reset()
            while not board.is_game_over() and board.fullmove_number < 100:
                if board.turn == chess.WHITE:
                    move = engine.play(board, chess.engine.Limit(time=0.01)).move
                else:
                    move = bot.get_move(board)
                board.push(move)

                if is_spectator:
                    output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, 'SIMULATING...')")
                    time.sleep(0.3)

            bot.stats["games"] += 1
            if board.result() == "0-1": bot.stats["wins"] += 1
            bot.save_brain()
            output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, '{get_status()}')")
            if is_spectator: time.sleep(2.0)
        engine.quit()
    except Exception as e: print(f"Error: {e}")

output.register_callback('notebook.handle_move', handle_move)
output.register_callback('notebook.run_sims', run_sims)

html_ui = f"""
<div style="text-align:center; background:#0a0a0a; color:#0f0; padding:20px; border:2px solid #0f0; border-radius: 10px; font-family:monospace; box-shadow: 0px 0px 15px #0f0;">
    <h2 style="text-shadow: 0px 0px 5px #0f0; margin-bottom: 5px;">WILLY V10: </h2>
    <div id="status" style="background:#111; padding:10px; border:1px solid #0f0; margin-bottom:10px; font-size:1.2em; font-weight:bold;">SYSTEM ONLINE</div>
    <p style="font-size: 1.1em;">GAMES: <span id="g_count">{bot.stats['games']}</span> | WINS: <span id="w_count">{bot.stats['wins']}</span></p>
    <div id="board" style="width:380px; margin:auto; border: 2px solid #333;"></div>

    <div style="margin-top:20px; display:flex; justify-content:center; gap:10px;">
        <button onclick="startSims(10)" style="padding:10px; background:#0f0; color:#000; border:none; cursor:pointer; font-weight:bold; transition: 0.2s;">SPECTATE 10</button>
        <button onclick="resetGame()" style="padding:10px; background:#444; color:#fff; border:1px solid #fff; cursor:pointer;">RESET 1V1</button>
        <button onclick="startSims(500)" style="padding:10px; background:#000; color:#0f0; border:1px solid #0f0; cursor:pointer;">GRIND 500</button>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.css">

<script>
var lock = false;
var board = Chessboard('board', {{
    draggable: true,
    position: 'start',
    orientation: 'white',
    onDrop: function(source, target) {{
        if (lock || source === target) return 'snapback';
        lock = true;
        $('#status').text("CALCULATING DEPTH (QUIESCENCE)...").css('color', '#ff0');

        google.colab.kernel.invokeFunction('notebook.handle_move', [source + target], {{}}).then(function(result) {{
            var parts = result.data['text/plain'].replace(/'/g, "").split('|');
            updateUI(parts[0], parts[1], parts[2], parts[3]);
            lock = false;
        }});
    }},
    pieceTheme: 'https://raw.githubusercontent.com/oakmac/chessboardjs/master/website/img/chesspieces/wikipedia/{{piece}}.png'
}});

function updateUI(fen, g, w, s) {{
    board.position(fen);
    $('#g_count').text(g);
    $('#w_count').text(w);
    let statusEl = $('#status');
    statusEl.text(s);

    if (s.includes("CHECKMATE")) {{
        statusEl.css({{"background": "#800", "color": "#fff"}});
    }} else if (s.includes("SIMULATING") || s.includes("CALCULATING")) {{
        statusEl.css({{"background": "#111", "color": "#ff0"}});
    }} else {{
        statusEl.css({{"background": "#111", "color": "#0f0"}});
    }}
}}

function resetGame() {{
    google.colab.kernel.invokeFunction('notebook.handle_move', ['RESET'], {{}}).then(function(res) {{
        var parts = res.data['text/plain'].replace(/'/g, "").split('|');
        updateUI('start', parts[1], parts[2], parts[3]);
        lock = false;
    }});
}}

function startSims(c) {{
    $('#status').text("SIMULATION INITIATED...").css('color', '#ff0');
    google.colab.kernel.invokeFunction('notebook.run_sims', [c], {{}});
}}
</script>
"""
display(HTML(html_ui))