# -*- coding: utf-8 -*-
"""wily v7 aka brain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqNsOpgDbLwfMz_JbP3_7FtpNikwAMkW
"""

!pip install python-chess
import chess
import json
from google.colab import output

!apt-get install stockfish

import chess
import chess.engine
import chess.svg
import random
import pickle
import os
import json
import math
import time
from IPython.display import HTML, display
from google.colab import output, drive

# --- 0. DRIVE SETUP ---
drive.mount('/content/drive', force_remount=True)
DB_PATH = "/content/drive/MyDrive/willy_brain_permanent.pkl"
WINS_DIR = "/content/drive/MyDrive/willy_wins/"
if not os.path.exists(WINS_DIR): os.makedirs(WINS_DIR)

# --- 1. THE ENGINE (V7.5 STRATEGIST) ---
class WillyV7:
    def __init__(self):
        self.stats = {"games": 0, "wins": 0}
        # Bishops > Knights slightly to favor long-term space control
        self.piece_values = {
            chess.PAWN: 100,
            chess.KNIGHT: 310,
            chess.BISHOP: 335,
            chess.ROOK: 500,
            chess.QUEEN: 950,
            chess.KING: 20000
        }
        self.load_brain()

    def load_brain(self):
        if os.path.exists(DB_PATH):
            try:
                with open(DB_PATH, 'rb') as f:
                    data = pickle.load(f)
                    self.stats = data.get('stats', {"games": 0, "wins": 0})
            except: pass

    def save_brain(self):
        with open(DB_PATH, 'wb') as f:
            pickle.dump({'stats': self.stats}, f)

    def evaluate_board(self, board):
        if board.is_checkmate():
            return 999999 if board.turn == chess.WHITE else -999999
        if board.is_stalemate(): return 0

        score = 0

        for sq, piece in board.piece_map().items():
            val = self.piece_values.get(piece.piece_type, 0)
            rank = chess.square_rank(sq)
            file = chess.square_file(sq)

            # --- BLACK (WILLY) LOGIC ---
            if piece.color == chess.BLACK:
                score += val

                # 1. THE PAWN PUSH: Bonus for advancing (Black moves 7 -> 0)
                if piece.piece_type == chess.PAWN:
                    score += (7 - rank) * 15

                    # 2. PAWN CHAINS: Bonus if pawn is defended by another pawn
                    defenders = board.attackers(chess.BLACK, sq)
                    for d_sq in defenders:
                        if board.piece_at(d_sq) and board.piece_at(d_sq).piece_type == chess.PAWN:
                            score += 25

                # 3. CENTER DOMINANCE
                if sq in [chess.D4, chess.D5, chess.E4, chess.E5]:
                    score += 20

            # --- WHITE (ENEMY) LOGIC ---
            else:
                score -= val
                if piece.piece_type == chess.PAWN:
                    score -= rank * 15
                    defenders = board.attackers(chess.WHITE, sq)
                    for d_sq in defenders:
                        if board.piece_at(d_sq) and board.piece_at(d_sq).piece_type == chess.PAWN:
                            score -= 25

        # 4. MOBILITY (SPACE CONTROL)
        mobility = len(list(board.legal_moves))
        score += (mobility * 2 if board.turn == chess.BLACK else -mobility * 2)

        return score

    def minimax(self, board, depth, alpha, beta, maximizing):
        if depth == 0 or board.is_game_over():
            return self.evaluate_board(board)

        # Move Ordering: Pawns & Captures first
        moves = sorted(board.legal_moves, key=lambda m: (
            board.piece_at(m.from_square).piece_type == chess.PAWN,
            board.is_capture(m)), reverse=True)

        if maximizing:
            max_eval = -math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, False)
                board.pop()
                max_eval = max(max_eval, eval)
                alpha = max(alpha, eval)
                if beta <= alpha: break
            return max_eval
        else:
            min_eval = math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, True)
                board.pop()
                min_eval = min(min_eval, eval)
                beta = min(beta, eval)
                if beta <= alpha: break
            return min_eval

    def get_move(self, board):
        best_move = None
        max_val = -math.inf
        for move in board.legal_moves:
            board.push(move)
            val = self.minimax(board, 3, -math.inf, math.inf, False)
            board.pop()
            if val > max_val:
                max_val = val
                best_move = move
        return best_move

# --- 2. BRIDGE & SIMULATION ---
bot = WillyV7()
board = chess.Board()

def handle_move(move_uci):
    global board
    if move_uci == "RESET":
        board.reset()
        return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}"
    try:
        move = chess.Move.from_uci(move_uci)
        if move in board.legal_moves:
            board.push(move)
            if not board.is_game_over():
                board.push(bot.get_move(board))
    except: pass
    return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}"

def run_sims(count=10):
    global board
    count = int(count)
    is_spectator = True if count <= 10 else False
    # Ensure stockfish is installed in colab: !apt-get install stockfish
    try:
        engine = chess.engine.SimpleEngine.popen_uci("/usr/games/stockfish")
        engine.configure({"Skill Level": 2})
        for _ in range(count):
            board.reset()
            while not board.is_game_over() and board.fullmove_number < 100:
                move = engine.play(board, chess.engine.Limit(time=0.01)).move if board.turn == chess.WHITE else bot.get_move(board)
                board.push(move)
                if is_spectator:
                    output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']})")
                    time.sleep(0.4)
            bot.stats["games"] += 1
            if board.result() == "0-1": bot.stats["wins"] += 1
            bot.save_brain()
            output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']})")
        engine.quit()
    except Exception as e:
        print(f"Stockfish Error: {e}. Make sure to run '!apt-get install stockfish' first.")

output.register_callback('notebook.handle_move', handle_move)
output.register_callback('notebook.run_sims', run_sims)

# --- 3. THE FLAT UI ---
html_ui = f"""
<div style="text-align:center; background:#111; padding:20px; color:#0f0; font-family:monospace; border-radius:15px; border: 2px solid #333;">
    <h2 style="color:#fff;">WILLY V7 </h2>
    <p>GAMES: <span id="g_count">{bot.stats['games']}</span> | WINS: <span id="w_count">{bot.stats['wins']}</span></p>
    <div id="board" style="width:380px; margin:auto; border: 1px solid #555;"></div>
    <div style="margin-top:20px;">
        <button onclick="startSims(10)" id="wBtn" style="padding:10px; background:#0f0; border:none; cursor:pointer; font-weight:bold; color:#000;">SPECTATE 10</button>
        <button onclick="resetGame()" style="padding:10px; background:#444; color:#fff; border:none; cursor:pointer;">RESET 1V1</button>
        <button onclick="startSims(500)" id="gBtn" style="padding:10px; background:#222; color:#0f0; border:1px solid #0f0; cursor:pointer;">GRIND 500</button>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.css">
<script>
var board = Chessboard('board', {{
    draggable: true,
    position: 'start',
    orientation: 'black',
    onDrop: function(source, target) {{
        var move = source + target;
        google.colab.kernel.invokeFunction('notebook.handle_move', [move], {{}}).then(function(result) {{
            var parts = result.data['text/plain'].split('|');
            board.position(parts[0].replace(/'/g, ""));
            $('#g_count').text(parts[1]);
            $('#w_count').text(parts[2]);
        }});
    }},
    pieceTheme: 'https://chessboardjs.com/img/chesspieces/wikipedia/{{piece}}.png'
}});
function updateUI(fen, g, w) {{ board.position(fen); $('#g_count').text(g); $('#w_count').text(w); }}
function resetGame() {{ google.colab.kernel.invokeFunction('notebook.handle_move', ['RESET'], {{}}).then(function(r){{ board.start(); }}); }}
function startSims(c) {{ google.colab.kernel.invokeFunction('notebook.run_sims', [c], {{}}); }}
</script>
"""
display(HTML(html_ui))