# -*- coding: utf-8 -*-
"""wily v7.6 aka brain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqNsOpgDbLwfMz_JbP3_7FtpNikwAMkW
"""

!pip install python-chess
import chess
import json
from google.colab import output

!apt-get install stockfish

import chess
import chess.engine
import chess.svg
import random
import pickle
import os
import math
import time
from IPython.display import HTML, display
from google.colab import output, drive

# --- 0. DRIVE SETUP ---
drive.mount('/content/drive', force_remount=True)
DB_PATH = "/content/drive/MyDrive/willy_brain_permanent.pkl"

# --- 1. THE ENGINE ---
class WillyV7:
    def __init__(self):
        self.stats = {"games": 0, "wins": 0}
        self.piece_values = {
            chess.PAWN: 100, chess.KNIGHT: 310, chess.BISHOP: 335,
            chess.ROOK: 500, chess.QUEEN: 950, chess.KING: 20000
        }
        self.load_brain()

    def load_brain(self):
        if os.path.exists(DB_PATH):
            try:
                with open(DB_PATH, 'rb') as f:
                    data = pickle.load(f)
                    self.stats = data.get('stats', {"games": 0, "wins": 0})
            except: pass

    def save_brain(self):
        with open(DB_PATH, 'wb') as f:
            pickle.dump({'stats': self.stats}, f)

    def evaluate_board(self, board):
        if board.is_checkmate():
            return 999999 if board.turn == chess.WHITE else -999999
        if board.is_stalemate() or board.is_insufficient_material(): return 0
        score = 0
        white_material = 0
        for sq, piece in board.piece_map().items():
            val = self.piece_values.get(piece.piece_type, 0)
            if piece.color == chess.WHITE: white_material += val
            if piece.color == chess.BLACK:
                score += val
                if piece.piece_type == chess.PAWN: score += (7 - chess.square_rank(sq)) * 15
            else: score -= val
        if white_material < 1500:
            w_king, b_king = board.king(chess.WHITE), board.king(chess.BLACK)
            score += max(abs(chess.square_rank(w_king) - 3.5), abs(chess.square_file(w_king) - 3.5)) * 15
            score += (14 - chess.distance(b_king, w_king)) * 5
        return score

    def minimax(self, board, depth, alpha, beta, maximizing):
        if depth == 0 or board.is_game_over(): return self.evaluate_board(board)
        moves = sorted(board.legal_moves, key=lambda m: board.is_capture(m), reverse=True)
        if maximizing:
            max_eval = -math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, False)
                board.pop()
                max_eval = max(max_eval, eval)
                alpha = max(alpha, eval)
                if beta <= alpha: break
            return max_eval
        else:
            min_eval = math.inf
            for move in moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, True)
                board.pop()
                min_eval = min(min_eval, eval)
                beta = min(beta, eval)
                if beta <= alpha: break
            return min_eval

    def get_move(self, board):
        best_move = None
        max_val = -math.inf
        for move in board.legal_moves:
            board.push(move)
            val = self.minimax(board, 3, -math.inf, math.inf, False)
            board.pop()
            if val > max_val:
                max_val = val
                best_move = move
        return best_move

# --- 2. BRIDGE & SIMULATION ---
bot = WillyV7()
board = chess.Board()

def get_status():
    if board.is_checkmate(): return "CHECKMATE!"
    if board.is_stalemate(): return "STALEMATE!"
    if board.is_game_over(): return "DRAW / GAME OVER"
    return "LIVE"

def handle_move(move_uci):
    global board
    if move_uci == "RESET":
        board.reset()
        return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|READY"
    try:
        move = chess.Move.from_uci(move_uci)
        if move in board.legal_moves:
            board.push(move)
            if not board.is_game_over():
                board.push(bot.get_move(board))
    except: pass
    return f"{board.fen()}|{bot.stats['games']}|{bot.stats['wins']}|{get_status()}"

def run_sims(count=10):
    global board
    count = int(count)
    is_spectator = True if count <= 10 else False
    try:
        engine = chess.engine.SimpleEngine.popen_uci("/usr/games/stockfish")
        engine.configure({"Skill Level": 5})
        for _ in range(count):
            board.reset()
            while not board.is_game_over() and board.fullmove_number < 100:
                move = engine.play(board, chess.engine.Limit(time=0.01)).move if board.turn == chess.WHITE else bot.get_move(board)
                board.push(move)
                if is_spectator:
                    output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, '{get_status()}')")
                    time.sleep(0.4)

            # If the game ended, show it and WAIT a second before resetting the loop
            final_status = get_status()
            output.eval_js(f"updateUI('{board.fen()}', {bot.stats['games']}, {bot.stats['wins']}, '{final_status}')")

            bot.stats["games"] += 1
            if board.result() == "0-1": bot.stats["wins"] += 1
            bot.save_brain()

            if is_spectator: time.sleep(2.0) # Gives you 2 seconds to read the final score

        engine.quit()
    except Exception as e: print(f"Error: {e}")

output.register_callback('notebook.handle_move', handle_move)
output.register_callback('notebook.run_sims', run_sims)

# --- 3. THE UI ---
html_ui = f"""
<div style="text-align:center; background:#111; padding:20px; color:#0f0; font-family:monospace; border-radius:15px; border: 2px solid #333;">
    <h2 style="color:#fff; margin-bottom:5px;">WILLY V7.8</h2>
    <div id="status_bar" style="background:#222; color:#ff0; padding:8px; margin-bottom:10px; border: 1px solid #444; font-weight:bold; font-size:1.2em;">SYSTEM READY</div>
    <p>GAMES: <span id="g_count">{bot.stats['games']}</span> | WINS: <span id="w_count">{bot.stats['wins']}</span></p>
    <div id="board" style="width:380px; margin:auto; border: 1px solid #555;"></div>
    <div style="margin-top:20px;">
        <button onclick="startSims(10)" style="padding:10px; background:#0f0; border:none; cursor:pointer; font-weight:bold; color:#000;">SPECTATE 10</button>
        <button onclick="resetGame()" style="padding:10px; background:#444; color:#fff; border:none; cursor:pointer;">RESET 1V1</button>
        <button onclick="startSims(500)" style="padding:10px; background:#222; color:#0f0; border:1px solid #0f0; cursor:pointer;">GRIND 500</button>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.css">
<script>
var board = Chessboard('board', {{
    draggable: true,
    position: 'start',
    orientation: 'black',
    onDrop: function(source, target) {{
        var move = source + target;
        google.colab.kernel.invokeFunction('notebook.handle_move', [move], {{}}).then(function(result) {{
            var parts = result.data['text/plain'].split('|');
            updateUI(parts[0].replace(/'/g, ""), parts[1], parts[2], parts[3].replace(/'/g, ""));
        }});
    }},
    pieceTheme: 'https://chessboardjs.com/img/chesspieces/wikipedia/{{piece}}.png'
}});

function updateUI(fen, g, w, s) {{
    board.position(fen);
    $('#g_count').text(g);
    $('#w_count').text(w);

    let statusEl = $('#status_bar');
    statusEl.text(s);

    // Color Coding Logic
    if (s.includes("CHECKMATE")) {{
        statusEl.css({{"background": "#800", "color": "#fff"}});
    }} else if (s.includes("STALEMATE") || s.includes("DRAW")) {{
        statusEl.css({{"background": "#550", "color": "#fff"}});
    }} else if (s.includes("READY")) {{
        statusEl.css({{"background": "#222", "color": "#ff0"}});
    }} else {{
        statusEl.css({{"background": "#222", "color": "#0f0"}});
    }}
}}

function resetGame() {{
    google.colab.kernel.invokeFunction('notebook.handle_move', ['RESET'], {{}}).then(function(r){{
        board.start();
        updateUI('start', $('#g_count').text(), $('#w_count').text(), "READY");
    }});
}}
function startSims(c) {{ google.colab.kernel.invokeFunction('notebook.run_sims', [c], {{}}); }}
</script>
"""
display(HTML(html_ui))