# -*- coding: utf-8 -*-
"""wily v4 aka brain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqNsOpgDbLwfMz_JbP3_7FtpNikwAMkW
"""

!pip install python-chess
import chess
import json
from google.colab import output

!apt-get install stockfish

import chess
import chess.engine
import chess.svg
import random
import pickle
import os
import json
import math
from IPython.display import HTML, display
from google.colab import output, drive

# --- 0. DRIVE SETUP ---
drive.mount('/content/drive', force_remount=True)
DB_PATH = "/content/drive/MyDrive/willy_brain_permanent.pkl"
JSON_EXPORT_PATH = "/content/drive/MyDrive/willy_brain.json"
WINS_DIR = "/content/drive/MyDrive/willy_wins/"

if not os.path.exists(WINS_DIR):
    os.makedirs(WINS_DIR)

# --- 1. THE V6 OVERDRIVE CORE ---
PIECE_VALUES = {chess.PAWN: 100, chess.KNIGHT: 320, chess.BISHOP: 330, chess.ROOK: 500, chess.QUEEN: 900, chess.KING: 20000}

class WillyV6:
    def __init__(self):
        self.q_table = {}
        self.stats = {"games": 0, "wins": 0}
        self.history = []
        self.load_brain()

    def load_brain(self):
        if os.path.exists(DB_PATH):
            try:
                with open(DB_PATH, 'rb') as f:
                    data = pickle.load(f)
                    self.q_table = data.get('q_table', {})
                    self.stats = data.get('stats', {"games": 0, "wins": 0})
            except: pass

    def save_brain(self):
        with open(DB_PATH, 'wb') as f:
            pickle.dump({'q_table': self.q_table, 'stats': self.stats}, f)
        with open(JSON_EXPORT_PATH, 'w') as f:
            json.dump(self.q_table, f)

    def evaluate_board(self, board):
        """V6: Strategic evaluation beyond just counting pieces."""
        if board.is_checkmate():
            return -99999 if board.turn == chess.WHITE else 99999

        score = 0
        for sq in chess.SQUARES:
            p = board.piece_at(sq)
            if p:
                val = PIECE_VALUES.get(p.piece_type, 0)
                if p.color == chess.BLACK: # Willy is Black
                    score += val
                    # Bonus for controlling the center
                    if sq in [chess.D4, chess.D5, chess.E4, chess.E5]: score += 10
                else:
                    score -= val
        return score

    def minimax(self, board, depth, alpha, beta, maximizing_player):
        """V6: Predictive Simulation (Alpha-Beta Pruning)"""
        if depth == 0 or board.is_game_over():
            return self.evaluate_board(board)

        if maximizing_player:
            max_eval = -math.inf
            for move in board.legal_moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, False)
                board.pop()
                max_eval = max(max_eval, eval)
                alpha = max(alpha, eval)
                if beta <= alpha: break
            return max_eval
        else:
            min_eval = math.inf
            for move in board.legal_moves:
                board.push(move)
                eval = self.minimax(board, depth - 1, alpha, beta, True)
                board.pop()
                min_eval = min(min_eval, eval)
                beta = min(beta, eval)
                if beta <= alpha: break
            return min_eval

    def get_move(self, board, depth=3):
        """Combines Memory with Prediction."""
        state = board.fen().split(' ')[0]

        # 1. Check for Memory-based Instant Win
        if state in self.q_table:
            best_memory_move = max(self.q_table[state], key=self.q_table[state].get)
            if self.q_table[state][best_memory_move] > 50: # Only if it's a high-confidence win
                return chess.Move.from_uci(best_memory_move)

        # 2. V6 Calculation: Look-ahead
        best_move = None
        max_eval = -math.inf

        for move in board.legal_moves:
            board.push(move)
            eval = self.minimax(board, depth - 1, -math.inf, math.inf, False)
            board.pop()
            if eval > max_eval:
                max_eval = eval
                best_move = move

        return best_move if best_move else random.choice(list(board.legal_moves))

bot = WillyV6()
board = chess.Board()

# --- 2. BACKEND HANDLERS ---
def handle_move(move_uci):
    global board
    if move_uci == "RESET": board.reset()
    else:
        try:
            move = chess.Move.from_uci(move_uci)
            if move in board.legal_moves:
                board.push(move)
                if not board.is_game_over():
                    m = bot.get_move(board, depth=3) # High-level play
                    if m: board.push(m)
                if board.is_game_over():
                    if board.result() == "0-1":
                        bot.stats["wins"] += 1
                        svg_data = chess.svg.board(board, size=400)
                        with open(f"{WINS_DIR}v6_win_{bot.stats['games']}.svg", "w") as f: f.write(svg_data)
                    bot.save_brain()
        except: pass
    return f"{board.fen()}|0|{len(bot.q_table)}|{bot.stats['wins']}"

def run_sims(count=1000):
    global board
    engine = chess.engine.SimpleEngine.popen_uci("/usr/games/stockfish")
    engine.configure({"Skill Level": 0})

    for g in range(int(count)):
        board.reset()
        while not board.is_game_over() and board.fullmove_number < 60:
            if board.turn == chess.WHITE:
                res = engine.play(board, chess.engine.Limit(time=0.00001))
                board.push(res.move)
            else:
                m = bot.get_move(board, depth=2) # Depth 2 for fast training
                board.push(m)

        if board.result() == "0-1":
            bot.stats["wins"] += 1
            svg_data = chess.svg.board(board, size=400)
            with open(f"{WINS_DIR}v6_sim_win_{bot.stats['games']}.svg", "w") as f: f.write(svg_data)

        bot.stats["games"] += 1
        if g % 10 == 0:
            output.eval_js(f"updateUI('{board.fen()}', 0, {len(bot.q_table)}, {bot.stats['wins']})")

    engine.quit()
    bot.save_brain()
    return "DOMINATION_COMPLETE"

output.register_callback('notebook.handle_move', handle_move)
output.register_callback('notebook.run_sims', run_sims)

# --- 3. RETRO UI ---
html_ui = f"""
<div id="root" style="text-align:center; font-family: monospace; background: #000; padding: 20px; color: #0f0; border: 2px solid #333;">
    <h3 style="margin:0; color:#fff;">WILLY V6 </h3>
    <div style="display: flex; justify-content: space-around; margin: 10px 0; font-size: 12px; color: #888;">
        <div>MEM: <span id="mem_val" style="color:#0f0;">{len(bot.q_table)}</span></div>
        <div>WINS: <span id="win_val" style="color:#0f0;">{bot.stats['wins']}</span></div>
    </div>
    <div id="myBoard" style="width: 350px; margin: auto; border: 1px solid #444;"></div>
    <div style="margin-top: 15px; display: flex; justify-content: center; gap: 10px;">
        <button onclick="resetGame()" style="padding: 8px; background: #222; color: #0f0; border: 1px solid #0f0; cursor: pointer;">RESET</button>
        <button onclick="startSims()" id="simBtn" style="padding: 8px; background: #0f0; color: #000; border: none; font-weight: bold; cursor: pointer;">1K</button>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@chrisoakman/chessboardjs@1.0.0/dist/chessboard-1.0.0.min.css">
<script>
var board = Chessboard('myBoard', {{ draggable: true, position: 'start', onDrop: onDrop, pieceTheme: 'https://chessboardjs.com/img/chesspieces/wikipedia/{{piece}}.png' }});
function updateUI(fen, elo, mem, wins) {{ board.position(fen); $('#mem_val').text(mem); $('#win_val').text(wins); }}
function onDrop(src, tgt) {{
    var uci = src + tgt;
    google.colab.kernel.invokeFunction('notebook.handle_move', [uci], {{}}).then(function(res) {{
        var p = res.data['text/plain'].split('|');
        updateUI(p[0].replace(/'/g, ""), 0, p[2], p[3]);
    }});
}}
function startSims() {{
    $('#simBtn').text('EXECUTING...').prop('disabled', true);
    google.colab.kernel.invokeFunction('notebook.run_sims', [1000], {{}}).then(function() {{
        $('#simBtn').text('START 1K WIN STREAK').prop('disabled', false);
    }});
}}
function resetGame() {{
    google.colab.kernel.invokeFunction('notebook.handle_move', ["RESET"], {{}}).then(function(res) {{
        var p = res.data['text/plain'].split('|');
        updateUI(p[0].replace(/'/g, ""), 0, p[2], p[3]);
    }});
}}
</script>
"""
display(HTML(html_ui))